language: python
python:
  - "3.6"

before_script:
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
    - ./integration_test.sh
    - ./test.sh
    - cat requirements/*.txt >requirements.txt
    - fossa init
    - fossa analyze
